/**
 * Regenerate `src/components/logo-artwork.js` from Figma exports.
 *
 * The logo is brand artwork, not code: it changes when the brand changes, and
 * it should change by re-export rather than by hand-editing path data. This
 * script is how that re-export lands.
 *
 * Export the two variant symbols from the Linchpin Brand file as SVG — the
 * `style=Primary` member of each, because the tones differ only in fill and
 * this script reads the fills to decide which paths are ink and which are the
 * ring — then:
 *
 *     node scripts/import-logo.mjs mark.svg lockup.svg
 *
 * File O78uQ8sRE44ZwAjRYHSrZI · brandmark 16410:26737 · primary-logo 15046:448
 */

import { readFileSync, writeFileSync } from 'node:fs';

const ACCENT = '#3fc1d0';
const OUT = new URL( '../src/components/logo-artwork.js', import.meta.url );

/**
 * The logo paths in an export, with Figma's frame chrome dropped.
 *
 * A symbol export carries the frame's background rect and a border path whose
 * coordinates run to the thousands. The artwork sits inside the viewBox, so
 * anything wildly outside it is chrome.
 *
 * @param {string} file Path to an exported SVG.
 * @return {{viewBox: string, ink: string[], accent: string[]}} The artwork.
 */
function read( file ) {
	const svg = readFileSync( file, 'utf8' );
	const viewBox = svg.match( /viewBox="([^"]+)"/ )?.[ 1 ];

	if ( ! viewBox ) {
		throw new Error( `${ file }: no viewBox.` );
	}

	const ink = [];
	const accent = [];

	for ( const match of svg.matchAll( /<path\s+([^>]*?)\/>/gs ) ) {
		const attrs = match[ 1 ];
		const d = attrs.match( /\sd="([^"]+)"/ )?.[ 1 ];

		if ( ! d ) {
			continue;
		}

		const numbers = [ ...d.matchAll( /-?\d+\.?\d*/g ) ].map( Number );

		if ( numbers.some( ( n ) => n < -200 || n > 1000 ) ) {
			continue;
		}

		const fill = (
			attrs.match( /fill="([^"]+)"/ )?.[ 1 ] ?? ''
		).toLowerCase();
		( fill === ACCENT ? accent : ink ).push( d );
	}

	if ( ! ink.length || ! accent.length ) {
		throw new Error(
			`${ file }: expected both ink and ${ ACCENT } paths, found ${ ink.length } and ${ accent.length }. Export the style=Primary variant.`
		);
	}

	return { viewBox, ink, accent };
}

const [ markFile, lockupFile ] = process.argv.slice( 2 );

if ( ! markFile || ! lockupFile ) {
	console.error(
		'Usage: node scripts/import-logo.mjs <mark.svg> <lockup.svg>'
	);
	process.exit( 1 );
}

const mark = read( markFile );
const lockup = read( lockupFile );

const list = ( paths ) => paths.map( ( d ) => `\t\t'${ d }',` ).join( '\n' );

const artwork = ( name, art ) => `export const ${ name } = {
	viewBox: '${ art.viewBox }',
	ink: [
${ list( art.ink ) }
	],
	accent: [
${ list( art.accent ) }
	],
};`;

writeFileSync(
	OUT,
	`/*
 * The Linchpin logo, exported from the brand file.
 *
 * Generated by scripts/import-logo.mjs — do not edit by hand. Re-export from
 * Figma and re-run the script instead, so the artwork in the package is
 * always something the brand file can be diffed against.
 *
 * Source: Figma O78uQ8sRE44ZwAjRYHSrZI
 *   brandmark    16410:26737 (style=Primary)
 *   primary-logo 15046:448   (style=Primary)
 *
 * \`ink\` is the wordmark and the mark's arm; \`accent\` is the ring. The brand's
 * tones differ only in how those two are filled — Primary is black ink, On
 * Dark is white ink, and the ring stays Linchpin blue in both — which is why
 * one set of geometry serves every tone.
 */

${ artwork( 'MARK', mark ) }

${ artwork( 'LOCKUP', lockup ) }
`
);

console.log(
	`Wrote ${ OUT.pathname }: mark ${ mark.ink.length } ink + ${ mark.accent.length } accent, lockup ${ lockup.ink.length } ink + ${ lockup.accent.length } accent.`
);
